AddCSLuaFile( "containers.lua" )
AddCSLuaFile( "items.lua" )
AddCSLuaFile( "trading.lua" )
AddCSLuaFile( "player.lua" )
AddCSLuaFile( "shared.lua" )
AddCSLuaFile( "config.lua" )
AddCSLuaFile( "properties.lua" )
AddCSLuaFile( "admin.lua" )
AddCSLuaFile( "gamemodes.lua" )

AddCSLuaFile( "cl_init.lua" )
AddCSLuaFile( "cl_menu.lua" )